### PR TITLE
Use broadcast_axes on 0.7

### PR DESCRIPTION
**Pull request by ararslan**
Fixes a deprecation warning.

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like the 0.7 broadcast changes broke the crazy broadcast hacking here. Effort is likely better spent updating packages not to use `Nullable` than trying to fix this.

**Comment by nalimilan** [comment]
Yes, it's going to require some work if we want to port this to the new system. It would be nice to do that, though, since the deprecation recommends using this package. We could change the deprecation to recommend using `Union{T, Nothing}`, but it wouldn't be a perfect replacement.

**Comment by ararslan** [comment]
Yeah, at this point I think we should just change the deprecation. Ideally this package will be buried beneath the sands of time, but as long as we keep pointing people to it, those people will be expecting us to maintain it.

**Comment by omus** [comment]
@ararslan sorry, I did the work and the package now works with https://github.com/JuliaArchive/Nullables.jl/pull/17

**Comment by ararslan** [comment]
Oh nooooooo 😉

**Pull request closed without merging**
