### PR TITLE
Fix _nullable_eltype

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, but is this enough to fix `broadcast`? With the failing tests it's hard to tell.

**Comment by davidanthoff** [comment]
No, it isn't. But it is enough to not block me from updating DataValues.jl, which I need to get up and running before I can tackle the whole remaining Queryverse stuff. Once I'm through with that I'll probably go back and try to get rid of the dependency on Nullables in the first place, but right now I'm mostly just trying to get things to run on 0.7.

**Review by nalimilan — APPROVED** [review]
OK, why not. This is going to require a lot of work to port fully to the new `broadcast` machinery.

**Comment by davidanthoff** [comment]
Bump, could we merge this and then tag a new release? I need this to continue with the Queryverse julia 0.7 compat work. Thanks!

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/15598. Out of curiosity, why does DataValues need this? AFAICT the package doesn't depend on Nullables.

**Comment by davidanthoff** [comment]
Thanks!

It uses ``_nullable_eltype`` somewhere, so strictly speaking I just need that for the time being. My strategy right now is to just get things working on 0.7, and so for now DataValues.jl will take a dependency on Nullables.jl, until I remove the need for that later.

**Comment by nalimilan** [comment]
If I were you I'd avoid depending on Nullables if you just need to copy a few functions, as it's not clear when/whether it will be fully ported to 0.7.

**Comment by davidanthoff** [comment]
For now all I need works, and once I’m done with getting things up and running on 0.7, I’ll make sure to drop that dependency. 

Having said that, wasn’t this package created for 0.7? It doesn’t really have any use on 0.6, right?

**Comment by nalimilan** [comment]
> Having said that, wasn’t this package created for 0.7? It doesn’t really have any use on 0.6, right?

Yes, but the broadcast machinery has been revamped since the package was created, and porting it will require some work that not many people will be interested in I guess...

**Comment by davidanthoff** [comment]
Yeah, that seems fair enough. I’m trying to wrap my head around the new broadcast design right now, not exactly easy...

**Pull request merged**
